//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class js_DNNJuliusFormArchivo
    {
        public long Id { get; set; }
        public Nullable<long> DNNJuliusFormId { get; set; }
        public string RutaFisica { get; set; }
        public string Fuente { get; set; }
    
        public virtual js_DNNJuliusForm js_DNNJuliusForm { get; set; }
    }
}
